// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX21Poj40p6ksrnP4q6bXHDx0FPZpagO0',
    appId: '1:1080510314949:web:3d7323094bdd46721333ac',
    messagingSenderId: '1080510314949',
    projectId: 'nusantara-internship-test',
    authDomain: 'nusantara-internship-test.firebaseapp.com',
    storageBucket: 'nusantara-internship-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9tK6AB9fgy7I1Jfsf-NXG1p9b8t_xDM',
    appId: '1:1080510314949:android:3595a17d4eed3ec51333ac',
    messagingSenderId: '1080510314949',
    projectId: 'nusantara-internship-test',
    storageBucket: 'nusantara-internship-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgLhtlkaN3NTOrRBFJrwbRPXVS_KWsLrM',
    appId: '1:1080510314949:ios:333b33f333cea8821333ac',
    messagingSenderId: '1080510314949',
    projectId: 'nusantara-internship-test',
    storageBucket: 'nusantara-internship-test.appspot.com',
    iosClientId: '1080510314949-fofdp4ge94vbastnah9u1ekb8fmlc1l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nusantaraAndroidDeveloperTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgLhtlkaN3NTOrRBFJrwbRPXVS_KWsLrM',
    appId: '1:1080510314949:ios:83b0d9991ac610091333ac',
    messagingSenderId: '1080510314949',
    projectId: 'nusantara-internship-test',
    storageBucket: 'nusantara-internship-test.appspot.com',
    iosClientId: '1080510314949-g12tkmicuhbl1evlg7k61lh0947j9pea.apps.googleusercontent.com',
    iosBundleId: 'com.example.nusantaraAndroidDeveloperTest.RunnerTests',
  );
}
